### ISSUE TITLE
Wifi breakers

### ISSUE THREAD

**Issue by hajopaj** [AMoo-Miki/homebridge-tuya-lan#17]
Hi,

I bought some wifi breakers like these 

https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.de%2Fulk%2Fitm%2F183495731099

over the internet and am wondering if I could get them to work in homebridge.

Your Plugin connects to the devices correctly but the whole „ready to handle“ part is missing.

I had a similar issue with „homebridge-tuya“ where the devices were recognized but could not be switched in homebridge.

https://github.com/codetheweb/homebridge-tuya/issues/39

Everything works in the Tuya-app though...

Any idea whats causing the problems?

**Comment by AMoo-Miki** [comment]
Hi,

Can you share some log?  If I understand correctly, you see the `Connected to` message but you don't see the `Ready to handle ... with signature` message. 

Discovery and initial connection are dependent on a correct `id`. If you see `Connected to` that means your `id` was good; if you don't, we need to go through the process of finding your `id` from scratch.

After successfully connecting, if you don't see `Ready to handle ... with signature` it could be either because the `key` was not good or that the device is not following the standard. In this case, I would recommend trying doing the `id` and `key` extraction from scratch.

If non of these helped, lemme know and I will try to procure one of these and check it out. Please update me.

Good luck.

**Comment by hajopaj** [comment]
Unfortunately both devices now quit working completely due to some overload or something...
I had to buy two new ones and choose some from eMylo to work with. I'm still trying to figure out how to get them to work with your plugin though and will keep you updated whether I was successful.

Any idea though which "type" to put in config.json?

**Comment by AMoo-Miki** [comment]
Both `SimpleLight` and `Outlet` would work fine for this. I recommend you start with `SimpleLight` that has some logging capabilities which will help discover any additional functionality that the device might have.

**Comment by AMoo-Miki** [comment]
Closed for inactivity. Please reopen if you still need help.
