### ISSUE TITLE
Specify IP addresses for vlans

### ISSUE THREAD

**Issue by AdmiralMichael** [AMoo-Miki/homebridge-tuya-lan#18]
Hello,

I recently switched to homebridge-tuya-lan from homebridge-tuya since that plugin has been deprecated. I had that plugin working fine with my vlans because I was able to specify the IP addresses of my devices. 

The auto discovery doesn't seem to find any outlets which was the same with homebridge-tuya until I added the ip option. 

It is possible for this field to be added?

Thanks,
AdmiralMichael

**Comment by AMoo-Miki** [comment]
With the latest update, you can explicitly define an `ip` for a device. To get the latest version before a release is made, run `npm i -g AMoo-Miki/homebridge-tuya-lan`.

The plugin prefers to discover devices on its own because there is some more information it can obtain during discovery so it waits for a minute. If the device doesn't reply to a discovery request, the `ip` will be used to connect to it.
