### ISSUE TITLE
Device addition

### ISSUE THREAD

**Issue by tonysprenk** [AMoo-Miki/homebridge-tuya-lan#28]
Thermostat switch for electric or water heating.

signature: 

{"1":false,"2":150,"3":155,"4":"Program","6":false,"12":0,"101":false,"102":false,"103":0,"104":1,"105":15,"106":true,"107":true,"108":true,"109":0,"110":10,"111":2,"112":45,"113":5,"114":35,"115":5,"116":"in","117":"keep","118":"2days"}

https://www.aliexpress.com/item/WIFI-Smart-Thermostat-16A-AC220V-Water-Electric-Floor-Heating-Temperature-Regulator-Weekly-Programmable-Temperature-Controller/32889265969.html?spm=2114.search0104.3.135.a7635628GDXQSy&ws_ab_test=searchweb0_0,searchweb201602_2_10065_10068_10890_319_10546_317_10548_10696_10084_453_454_10083_10618_10304_10307_10820_537_536_10902_10843_10059_10884_10887_321_322_10103-10890,searchweb201603_51,ppcSwitch_0&algo_expid=2b435365-e68d-4168-9186-19bd53e75d49-18&algo_pvid=2b435365-e68d-4168-9186-19bd53e75d49

**Comment by AMoo-Miki** [comment]
@tonysprenk, I would need your help in finding out what each of those parameters are. Define the device as `SimpleLight` which you already have. Monitor the logs while you use the device itself to change things one at a time. Note down what you did and what change you saw in the log.

There are 2 sets of things we need to find out: (1) what data-point matches a certain function, and (2) what values correspond to different states of that function. There are somethings that HomeKit doesn't support yet, such as on-device timers, but documenting them here will help us add the functionality if HomeKit chooses to implement them at a later time.

**Comment by tonysprenk** [comment]
I will get to this later today. I already did some research with Max over at Homebridge-Tuya

https://github.com/codetheweb/homebridge-tuya/pull/45
https://github.com/codetheweb/homebridge-tuya/issues/43

I also have a curtain switch, it was implemented in Homebridge-Tuya also.

https://github.com/codetheweb/homebridge-tuya/issues/5
https://github.com/codetheweb/homebridge-tuya/issues/37
https://github.com/codetheweb/homebridge-tuya/issues/35

**Comment by AMoo-Miki** [comment]
Cool. I see that only data points 2 and 3 were implemented which refer to the desired temperature and current temperature. I would prefer to use this opportunity to implement as much as we can.

I looked at the images  and earlier messages, and from what I gather:
1: Screen on/off
2: Desired temp (10x C)
3: Current temp (10x C)
4: Mode: Manual, which I presume is you set the temp manually; Programming, which I guess will regulate the temp to be between 114 and 115. (?)
112: Highest temperature allowed for manual setting (?)
113: Lowest temperature allowed for manual setting (?)
114: Highest desired temperature in Programming (Auto) mode (?)
115: Lowest desired temperature in Programming (Auto) mode (?)
116-118: Programming related which can't be handled by HomeKit

I am would love to know what all the others do so that we can add them.

Regarding your curtains, stay tuned; I will have the basic version out in a day or two.

**Comment by tonysprenk** [comment]
The above seems to be correct, it has a programming function where you can set the temperature for different days of the week ( 1 through 7) and it has a "Holliday" mode where it keeps a constant temperature throughout the week. In my case it is connected to underfloor heating which either needs to be on or off at certain times, the "switch" turns on when the set temperature is higher than the current temperature. but I understand the importance of knowing all the different functions. 

I pressed al the buttons on the device but nothing was showing up in the home bridge terminal window, am I doing something wrong?

**Comment by AMoo-Miki** [comment]
You will need the unreleased version of the plugin. My bad;  I thought I mentioned it earlier. Get it with `npm i -g AMoo-Miki/homebridge-tuya-lan`. Your efforts will make the life of many easier; thanks.

**Comment by PierreBrisorgueil** [comment]
@AMoo-Miki hey, some news on curtains ?

**Comment by AMoo-Miki** [comment]
@PierreBrisorgueil the discussion for curtains can be found on issue #22.
