### ISSUE TITLE
[TuyaAccessory] Closed connection with Air Conditioner error repeating

### ISSUE THREAD

**Issue by KrtNthny** [AMoo-Miki/homebridge-tuya-lan#72]
Hi,

I am having a problem with an error repeating in the log file even though everything is working fine.

The error is

> [TuyaAccessory] Closed connection with Air Conditioner

It just keeps repeating every second and fills the log file. but everything is working fine otherwise.

> [7/12/2019, 3:51:26 PM] [TuyaLan] Connected to Air Conditioner
> [7/12/2019, 3:51:26 PM] [homebridge-lib.Lib] warning: heartbeat 4, drift 646
> [7/12/2019, 3:51:26 PM] [Hue] Kurts hue bridge: Philips BSB002 bridge v1932126170, api v1.32.0
> [7/12/2019, 3:51:27 PM] [Hue] Kurts hue bridge: 1 accessories
> [7/12/2019, 3:51:27 PM] [TuyaLan] Ready to handle Air Conditioner with signature {"1":false,"2":30,"3":23,"4":"FAN","5":"1","19":"C","102":false,"103":0,"104":false,"105":0,"106":0,"110":"0"}
> [7/12/2019, 3:51:27 PM] [Hue] masked debug info dumped to /Users/kurt/.homebridge/homebridge-hue.json.gz
> [7/12/2019, 3:51:27 PM] [Hue] Initializing platform accessory 'Kurts hue bridge'...
> [7/12/2019, 3:51:27 PM] [Hue] Kurts hue bridge: 2 services
> Setup Payload:
> X-HM://0023ISYWY5H59
> Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
> [47m  [0m[47m  [0m[47m  [0m[47m  [0m[47m  [0m[47m  [0m[47m  [0m[47m  [0m[47m  
> Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
>                        
>     ┌────────────┐     
>     │ 031-45-154 │     
>     └────────────┘     
>                        
> [7/12/2019, 3:51:27 PM] Homebridge is running on port 51888.
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> (node:69) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner
> [TuyaAccessory] Closed connection with Air Conditioner

**Comment by carsten-h** [comment]
I have the same issue here. The device is always another one. But everything is working.

**Comment by bugs181** [comment]
Can confirm. Just started happening to me as well. Stack overflow.

Here's my log:


<details>
<summary>Homebridge log</summary>

... good night scene activated
...
[TuyaAccessory] Sending Bedside Fan {"1":true}
...
[TuyaAccessory] Closed connection with Bedside Fan
[TuyaAccessory] Closed connection with Bedside Fan
[TuyaAccessory] Closed connection with Bedside Fan
... repeats thousands of times
[TuyaAccessory] Closed connection with Bedside Fan
(node:2318) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit
[TuyaAccessory] Closed connection with Bedside Fan
[TuyaAccessory] Closed connection with Bedside Fan
[TuyaAccessory] Closed connection with Bedside Fan
.. repeats thousands of times

<--- Last few GCs --->

[2318:0x103001600] 346139733 ms: Mark-sweep 1413.5 (1488.0) -> 1413.5 (1468.0) MB, 1054.2 / 1.7 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1054 ms) last resort 
[2318:0x103001600] 346141890 ms: Mark-sweep 1413.5 (1468.0) -> 1413.5 (1468.0) MB, 2156.7 / 1.6 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x670f791cca1 <JSObject>
    1: destroy [internal/streams/destroy.js:~4] [pc=0xf5b9dc473aa](this=0x1eb4d9914971 <Socket map = 0x38041edc2261>,err=0x173b06d7d481 <Error map = 0x38041edf6139>,cb=0x670f7902241 <undefined>)
    2: arguments adaptor frame: 1->2
    3: internalConnect(aka internalConnect) [net.js:~878] [pc=0xf5b9dc8f54a](this=0x670f7902241 <undefined>,self=0x1eb4d9914971 <Socket map = 0x38041edc2261>,address=0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::compiler::CodeGenerator::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [/usr/local/bin/node]
 6: v8::internal::compiler::CodeGenerator::FinalizeCode() [/usr/local/bin/node]
 7: v8::internal::compiler::PipelineImpl::FinalizeCode() [/usr/local/bin/node]
 8: v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl() [/usr/local/bin/node]
 9: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [/usr/local/bin/node]
10: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [/usr/local/bin/node]
11: v8::internal::StackGuard::HandleInterrupts() [/usr/local/bin/node]
12: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0xf5b9ca040dd
Abort trap: 6

</details>

**Versions:**
**OS:** macOS Sierra (10.12.6)
**node:** v8.3.0
**homebridge:** 0.4.50
**homebridge-tuya-lan:** 1.2.1

**Comment by TheHomekitWayFinder** [comment]
I have an air conditioner and whenever I put the code into my config file Homebridge crashes, so I’m presuming it’s something to do with the plugin not being up to date with the TuyApi repository by CodeTheWeb

**Comment by KrtNthny** [comment]
Did you check the homebridge log for any error?

**Comment by verisgit** [comment]
Not sure this is supported anymore (since the Tuya/Smartlife patch). I've never been able to get it to work with my device and can't get a response from anyone to confirm if it's still supported.

**Comment by AMoo-Miki** [comment]
From the log, the signature was identified but for some reason the device terminated the connection. I have pushed logic to slow down the reconnects to avoid crashing. Update the plugin to at least have it running without crashing everything. Take a look at the [Common Problems](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Common-Problems) page to see if anything there helps you.

**Comment by AMoo-Miki** [comment]
Please give the latest `rc` release a shot by doing `npm i -g homebridge-tuya-lan@rc`. It includes logic to understand this newer API.

A known issue is that the current state is not reported by some devices; they however work fine as soon as you interact with them. I have reached out to Tuya for a solution. 

The [Setup Instructions](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Setup-Instructions) have changed in case you need to obtain a fresh `id` and `key`.

**Comment by KrtNthny** [comment]
Hey, 

I’m not sure if you’re doing this for my issue alone but because the SmartLife app now works with Siri Shortcuts app, I can setup shortcuts to do most of the things Homebridge can do so I haven’t been using the Tuya-Lan and Homebridge anymore. 

Thank you.

**Comment by AMoo-Miki** [comment]
@KrtNthny that is great news; I had no idea. Someone from Tuya reached out to me a few weeks ago saying they are working on Homekit integration; let's hope they don't stop with just Siri shortcuts. Good luck. :)

@verisgit I will close this issue and work with you on the other issue you have open.

**Comment by KrtNthny** [comment]
Thanks, I tried the plugin again using `npm i -g homebridge-tuya-lan@rc` and I am not getting that repeating error.

I had to try this because after iOS 13 update shortcuts are not working on HomePod or Apple Watch so having the Air Conditioner in Home is much more convenient.

Thank you.

**Comment by AMoo-Miki** [comment]
@KrtNthny If you restart Homebridge, does the device show up?

**Comment by KrtNthny** [comment]
No it didn’t. But it did come back eventually somehow.
